### ISSUE TITLE
Simple vector fields over flat surfaces example missing

### ISSUE THREAD

**Issue by cpandar** [agosztolai/MARBLE#24]
From the Readme:

> We suggest you study at least the example of a [simple vector fields over flat surfaces](https://github.com/agosztolai/MARBLE/blob/main/examples/ex_vector_field_flat_surface.py) to understand what behaviour to expect.

However the [link](https://github.com/agosztolai/MARBLE/blob/main/examples/ex_vector_field_flat_surface.py) seems to be broken. 

Thanks!

**Comment by agosztolai** [comment]
Dear Chetan, 

Thanks for spotting this. We have slightly changed the folder structure and the link was not updated. [Here](https://github.com/agosztolai/MARBLE/blob/main/examples/toy_examples/ex_vector_field_flat_surface.py) is the fixed link. You can also find other toy examples in [this](https://github.com/agosztolai/MARBLE/blob/main/examples/toy_examples/) folder.

Best, 
Adam

**Comment by cpandar** [comment]
Excellent, thanks!
